steps:
    - bash: |
        docker build . -t b:$(git rev-list -1 HEAD)
      workingDirectory: services/b
      displayName: Build Docker image
      condition: and(succeeded(), eq(variables.updated, 'true'))