steps:
    - bash: |
        docker build . -t a:$(git rev-list -1 HEAD)
      workingDirectory: services/a
      displayName: Build Docker image
      condition: and(succeeded(), eq(variables.updated, 'true'))