steps:
    - bash: |
        docker build . -t c:$(git rev-list -1 HEAD)
      workingDirectory: services/c
      displayName: Build Docker image
      condition: and(succeeded(), eq(variables.updated, 'true'))